sonar.sources=.
sonar.exclusions=build,public/build,coverage
sonar.coverage.exclusions=**/__mocks__/**,src/routes/**,src/mocks/**
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
